version: '3.5'
services:
  discovery:
    image: xprem/discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image: xprem/service-gateway
    container_name: service-gateway
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  account-service:
    image: xprem/payment-service
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  customer-service:
    image: xprem/customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile

    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_PROFILES_ACTIVE: prod
    links:
      - discovery